//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMBTSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.IssueLogTimes = new HashSet<IssueLogTime>();
            this.Logins = new HashSet<Login>();
        }
    
        public int IssueID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public Nullable<int> IssueStatusID { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public System.DateTime TimeEstimation { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual IssueStatus IssueStatu { get; set; }
        public virtual Project Project { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual ICollection<IssueLogTime> IssueLogTimes { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
