//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMBTSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueLogTime
    {
        public int LoginID { get; set; }
        public int IssueID { get; set; }
        public System.DateTime IssueTime { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Login Login { get; set; }
    }
}
