//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMBTSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueStatus
    {
        public IssueStatus()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int IssueStatusID { get; set; }
        public string IssueStatusName { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
