//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMBTSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.IssueLogTimes = new HashSet<IssueLogTime>();
            this.Issues = new HashSet<Issue>();
        }
    
        public int LoginID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<IssueLogTime> IssueLogTimes { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
