//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMBTSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDiscription { get; set; }
        public System.DateTime ProjectStartDate { get; set; }
        public System.DateTime ProjectFinishDate { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
